### ISSUE TITLE
Clear up compiler warnings

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/contracts#255]
Compiling our contracts currently returns a large number of compiler warnings. 

Fixing them should be a fairly simple task, but will require some time to go through everything. 

**Recommended approach:**

IMO the solc binary give much easier to read colored output compared to hardhat, so install `solc` 
1. Install `solc` verson 0.7.6 following [these instructions](https://docs.soliditylang.org/en/v0.7.6/installing-solidity.html) (any of the methods described on that page _other than_ `npm i -g solc` because `solcjs != solc`!). 
2. `cd` into the root of this repo. 
3. Run the compiler on the full system using: `solc --allow-paths . contracts/optimistic-ethereum/**/*.sol` 
4. Work through the warnings systematically. You might choose to focus on one file at a time, or one type of warning at a time, whichever works for you. 

I would suggest submitting a draft PR for early review after clearing up the first dozen or so warnings, just to be sure we're on track.

**Comment by maurelian** [comment]
This was partially fixed by #265, but remains a WIP.

**Comment by N3r0m5ns3r** [comment]
when compiling with solc

**Comment by maurelian** [comment]
@N3r0m5ns3r I'm not having any such errors on master.

**Comment by N3r0m5ns3r** [comment]
Weird I am compiling from the master branch still getting the same errors. maybe there is something wrong with my system or configuration.
