### ISSUE TITLE
Decimals broken on oWETH

### ISSUE THREAD

**Issue by geohot** [ethereum-optimism/contracts#271]
Decimals is using an immutable variable, which isn't getting set correctly in the constructor. You can fix this by removing immutable, and I can confirm decimals works, but that moves the storage slots which breaks my existing chain.

**Comment by geohot** [comment]
Immutable don't work on OVM_ETH, because you are replacing the code after you run the constructor. See contract-dumps.ts.

**Comment by kfichter** [comment]
Issue is specifically here: https://github.com/ethereum-optimism/contracts/blob/35461406b1c9b3e2715509f79b33da78add17458/src/contract-dumps.ts#L202-L212

**Comment by smartcontracts** [comment]
@ben-chain is this fixed yet?

**Comment by ben-chain** [comment]
This is now fixed, yep!
