### ISSUE TITLE
OVM_L1ETHGateway references ERC20 in comments

### ISSUE THREAD

**Issue by samajammin** [ethereum-optimism/contracts#321]
**Describe the bug**

Hey folks!

Perhaps I'm missing something but I was checking out the OVM_L1ETHGateway.sol contract:
https://github.com/ethereum-optimism/contracts/blob/master/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ETHGateway.sol

[The `deposit()` function comment states "deposit an amount of the ERC20 to the caller's balance on L2"](https://github.com/ethereum-optimism/contracts/blob/master/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ETHGateway.sol#L60). Is that correct?

**Expected behavior**
My understanding is this bridge contract is for depositing ETH, not ERC20 tokens.

**Additional context**
Feel free to close this out if I'm incorrect 😅

**Comment by samajammin** [comment]
Related to this, it appears that the `iOVM_ERC20` interface [is imported but never used](https://github.com/ethereum-optimism/contracts/blob/master/contracts/optimistic-ethereum/OVM/bridge/tokens/OVM_L1ETHGateway.sol#L9).

**Comment by platocrat** [comment]
> **Expected behavior**
> My understanding is this bridge contract is for depositing ETH, not ERC20 tokens.

I was wondering the same thing. There's no native ETH on Optimistic Ethereum, so I wasn't sure if "ERC20" implied the conversion of ETH to WETH, or if there were just typos in the code comments.

**Comment by smartcontracts** [comment]
@samajammin Appears this is most likely an error in the comment. @ben-chain can you confirm?

**Comment by ben-chain** [comment]
This is definitely a typo, thanks @samajammin !  Will fix asap :)

**Comment by smartcontracts** [comment]
Could be a good ticket for someone on discord to pick up
