### ISSUE TITLE
Use ethers.constants.HashZero instead of NULL_BYTES32

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/contracts#339]
**Is your feature request related to a problem? Please describe.**
We're currently using a custom constant `NULL_BYTES32` all over the place: https://github.com/ethereum-optimism/contracts/blob/74f8f791839a91f3ea7f7d6fcb9136f05754e36d/test/helpers/constants.ts#L20-L21

It'd be much better if we used `ethers.constants.HashZero` so that we can outsource these constants to one place. Same idea as #329.

**Describe the solution you'd like**
Replace all instances of `NULL_BYTES32` with `ethers.constants.HashZero`. Please be careful not to replace `NON_NULL_BYTES32` by accident!

**Comment by Sullie404** [comment]
I am working on this now :)
