### ISSUE TITLE
Lib_MerkleTree overwrites elements of the input array when multiple elements are passed in

### ISSUE THREAD

**Issue by shanefontaine** [ethereum-optimism/contracts#344]
**Describe the bug**
The variable passed into the [`_elements`](https://github.com/ethereum-optimism/contracts/blob/master/contracts/optimistic-ethereum/libraries/utils/Lib_MerkleTree.sol#L23) function param of `Lib_MerkleTree.getMerkleRoot()` is unintentionally overwritten when `_elements.length > 1` and when the variable being passed in is stored as `memory`.

If the `_elements` array has a length of `n` where `n > 1`, all elements up to the final one are overwritten with an unexpected hash when execution continues after the completion of `getMerkleRoot()`.

**To Reproduce**
1. Paste [this](https://gist.github.com/shanefontaine/35d515b54690fd3243285b088323753d) gist into remix
2. Deploy ExampleContract
3. Pass in 2+ `bytes32` values as an array into `exampleFunction()`
4. Observe different values for `idBefore` and `idAfter`

**Expected behavior**
I would expect `idBefore` and `idAfter` to be the same value.

**Additional context**
I do not believe Optimism's current contracts are affected by this issue. However, future Optimism contracts may be. Additionally, developers and projects who fork this code or use the Lib_MerkleTree library may have issues.

**Comment by smartcontracts** [comment]
Ah. Hmm. This is actually intended behavior and meant to reduce the gas usage of our contracts since we don't need access to the elements once we compute the Merkle root. Perhaps the best available solution right now is to leave a detailed comment explaining this behavior.

**Comment by ben-chain** [comment]
This is a great callout Shane, thanks!!  Gonna merge this PR which clarifies exactly this; it is an intended optimization, so we do want it. https://github.com/ethereum-optimism/contracts/pull/336

**Comment by shanefontaine** [comment]
Understood and makes sense 👍
