### ISSUE TITLE
Remove Deployer, Place in own Repo

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/contracts#52]
The deployer now depends on ethers hardware wallet which in turn depends on node-hid which depends on having `libusb-1.0` installed in the containers. It would be better to remove the deployer script so that every container that installs the contracts doesn't need to also install the usb library. Note that containers without `libusb-1.0` can built, but it throws a nasty warning.

**Comment by kfichter** [comment]
@tynes is this still an issue?

**Comment by tynes** [comment]
Not a high priority but I think it would be nice once the contracts are frozen
